services:

  tinc-hostname-app:
    image: tiredofit/tinc:latest
    container_name: tinc-hostname-app
    hostname: hostname
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 655:655
    volumes:
      - ./data:/etc/tinc
      - ./logs:/var/log/tinc
    environment:
      - GIT_USER=username
      - GIT_PASS=password
      - GIT_URL=https://git.example.com/config/tinc-network
      - CONTAINER_NAME=tinc-hostname-app
      - CRON_PERIOD=5
      - DEBUG=1

      - NETWORK=example
      - NODE=hostname_example_org
      - PUBLIC_IP=123.123.123.249
      - PRIVATE_IP=172.22.0.43
      - INTERFACE=tun0
      - PEERS=hostname1_example_org hostname2_example_org
      - COMPRESSION=9
    network_mode: "host"

